### ISSUE TITLE
problems w/ new project

### ISSUE THREAD

**Issue by NicolasRouquette** [pawamoy/copier-pdm#26]
There are a few problems creating a new project from scratch:

1) If there is no python 3.7, I get errors like this:

```
make check-types
[NoPythonVersion]: No Python interpreter matching python3.7 is found.
make: *** [Makefile:52: check-types] Error 1
```

2) the template should prompt for the range of python versions we want

After the project was created, I updated `pyproject.toml` like this:

```
requires-python = ">=3.8,<3.12"
keywords = []
dynamic = ["version"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Documentation",
    "Topic :: Software Development",
    "Topic :: Utilities",
    "Typing :: Typed",
]
```

3) After this, I get errors like this:

```
make check
[NoPythonVersion]: No python is found meeting the requirement python >=3.8,<3.12
make: *** [Makefile:43: check] Error 1
```

Where is this version check coming from?

4) Looking at `pdm-multirun`, I wonder whether the `Makefile` should set `PDM_MULTIRUN_VERSIONS`

I tried it manually:

```
pdm multirun -i 3.11 duty check-types
Traceback (most recent call last):
  File "/home/nfr/.local/bin/duty", line 5, in <module>
    from duty.cli import main
ModuleNotFoundError: No module named 'duty'
```

This is surprising because I see in `pyproject.toml` the following:

```
[tool.pdm.dev-dependencies]
duty = ["duty>=0.10"]
```

Any suggestions on addressing these problems?

**Comment by pawamoy** [comment]
Hello, thanks for your interest in my template :slightly_smiling_face: 

> If there is no python 3.7, I get errors like this:

The documentation is not up-to-date, you can indeed set `PDM_MULTIRUN_VERSIONS` yourself to define the versions you want to use. You are also responsible for installing and making available the selected Python versions, through pyenv for example.

> After this, I get errors like this:

That must come from PDM. It's usually not a good idea to set an upper bound limit to your required Python version, unless you absolutely know your code won't work on Python 3.12.

> I tried it manually: ... No module named 'duty'

That's probably because dependency were not installed for Python 3.11.

Make sure to define the select available Python versions and to run `make setup`, for example:

```bash
PDM_MULTIRUN_VERSIONS="3.8 3.9 3.10 3.11" make setup
```

I'll add a documentation label :sli

**Comment by pawamoy** [comment]
Documentation updated.
